
name: heGUI
channels:
- conda-forge
- defaults
dependencies:
- python=3.7.3
- tk=8.6.11
- pyqt=5.12.3 
- pip
- pip:
    - git+https://github.com/ionpath/mibilib@v1.4.2
    - napari[all]
    - python-dotenv==0.20.0
    - scikit-image==0.18.0
