
name: heGUI
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- tk=8.6.11
- pip
- pip:
    - magicgui[pyqt5]
    - git+https://github.com/ionpath/mibilib@v1.4.1
    - napari[all]
    - python-dotenv==0.19.0
    - scikit-image==0.18.0
    - imagecodecs==2021.8.26
